apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hourglass-api
  description: |
    Security Leaderboard + Slackbot API Definition
spec:
  type: openapi
  lifecycle: production
  owner: test
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json 
