---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: templates
  annotations:
    github.com/project-slug: 'external-spotify-portal-demo/templates'
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: production
  owner: test
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hourglass-api
  description: |
    Security Leaderboard + Slackbot API Definition
spec:
  type: openapi
  lifecycle: production
  owner: test
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json 
